### ISSUE TITLE
Toinen versio: Datan generointi csv tiedostoon

### ISSUE THREAD

**Issue by perej1** [perej1/hill_simu#3]
Tein toisen version noiden korjausehdotusten perusteella. Nyt en plottaile vielä mitään vaan generoin vain estimaatteja parametrien n (otoskoko) ja r (estimaattien määrä) mukaan. Parametrit syötetetään vasta ajettaessa komentorivilla tyyliin "python3 hillSim.py -n 1000 -r 500" argparse kirjaston avulla. Tuloksena syntyy csv tiedosto, jossa on hill estimaatorin arvoja pareto ja cauchy jakaumille. Skripti on vielä varsin alkeellinen mutta ajattelin nyt lähteä koodaamaan vähän rauhallisemmin pala kerrallaan (toisin kuin ensimmäisessä versiossa).

**Comment by mapehe** [comment]
Jees nähin issueihin voi kommentoida niin ei tarvitse joka viestille luoda uutta issueta :)

Tuo toka versio on paljon enemmän sen näköinen mitä kelasin että se lopullinen koodi olisi, hyvä homma siis!  Sellainen yksittäinen juttu vielä että tuo k_n
https://github.com/perej1/hill_simu/blob/096bb3332f0ccce1a0795dcf4e614ca035f5b738/hillSim.py#L21-L22
voisi tämän sijaan olla komentoriviargumentti samoin kuin n ja r ovat nyt.

**Comment by mapehe** [comment]
Tän
https://github.com/perej1/hill_simu/blob/096bb3332f0ccce1a0795dcf4e614ca035f5b738/hillSim.py#L44-L48
voisi tehdä mielummin niin, että annettaisiin `str`-tyyppinen komentoriviargumentti ja sen arvon perusteella päätettäisiin sitten että kummasta jakaumasta simuloidaan otos.

**Comment by mapehe** [comment]
Tuo filu mihin kirjoitetaan tässä
https://github.com/perej1/hill_simu/blob/096bb3332f0ccce1a0795dcf4e614ca035f5b738/hillSim.py#L54
pitäisi kanssa oikeastaan olla komentoriviargumentti, jotta sitä olisi sitten helppo vaihtaa tarvittaessa

**Comment by perej1** [comment]
Lisäsin sinne nyt lisää noita komentoriviargumentteja ehdotusten perusteella. Nyt koodi ajetaan tyyliin "python3 hillSim.py -n <koko> -r <määrä> -k <k_n> -f <file_path> -d <distribution>".

**Comment by mapehe** [comment]
Jees oikein hyvältä näyttää laitoin pull requestiin #5 joitain ihan minimaalisia korjauksia jotka saat tuotua tähän sun repoon hyväksymällä sen.

Tän issuen vois melkein sulkea ja alkaa miettiä sitä plottailua huomisessa tapaamisessa.
