### ISSUE TITLE
Mean of empty slice

### ISSUE THREAD

**Issue by mapehe** [perej1/hill_simu#4]
Kun koitan ajaa `python hillSim.py -n 2000 -r 100`, saan seuraavan tulosteen

>/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

Luulen että tuossa
https://github.com/perej1/hill_simu/blob/096bb3332f0ccce1a0795dcf4e614ca035f5b738/hillSim.py#L31
lasketaan jostain syystä keskiarvoa tyhjän joukon yli. Tsekkaahan vielä että skripti toimii sulla. Jos toimii sulla mutta ei mulla niin lähdetään yhdessä metsästämään bugia.

**Comment by perej1** [comment]
Itse en saanut tuotettua samaa virhettä kun kokeilin pari kertaa ajaa scriptin noilla arvoilla. Itseasiassa minulla ei näkynyt edes issue1 virhettä testattaessa ensimmäisen version koodia.

**Comment by mapehe** [comment]
koitin toisella koneella niin mullakin toimi ok, ei siis oo skriptissä vika vaan työkoneen jossain paketeissa
